### ISSUE TITLE
ERROR: No CCD width available for camera

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/structure-from-motion#29]
Hey guys,
I was trying to run the pipeline via Docker. I'm getting this error:

chris@chris-desktop ~/pointclouds/images/kaars $ docker run -u $UID -v $PWD:/data nlesc/structure-from-motion
[- Creating list of images -]
[- Retrieved 32 images in 0.0 seconds -]
[- Extracting EXIF tags from images -]
[Extracting EXIF tags from image ./DSC_0001.jpg]
  [EXIF focal length = 18.0mm]
  [EXIF CCD width = 0mm]
  [EXIF resolution = 6000 x 4000]
ERROR: No CCD width available for camera NIKON CORPORATION NIKON D3300]
chris@chris-desktop ~/pointclouds/images/kaars $ 

I remember getting this warning a few weeks/months ago, about not knowing my camera, but it was only a warning then and it would just continue. Any flag I can use to continue anyway?

**Comment by jmaassen** [comment]
I've noticed that continuing without the proper CCD info usually lead to problems further in the pipeline. That's why I introduced the error message. 

I've added your camera to the list we have in run-sfm.py (according to google the CCD width is 23.5 mm), and pushed the change to github.

I'm not sure if this automatically propagates into the docker image however ? 

Niels do you know this ?

**Comment by nielsdrost** [comment]
Yes, this should automagically end up in the image.

See here: https://registry.hub.docker.com/u/nlesc/structure-from-motion/builds_history/161702/

**Comment by jmaassen** [comment]
OK, that means is should work now. 

Can you try again Christiaan ?

**Comment by nielsdrost** [comment]
Actually, it is still busy building I think

**Comment by jmaassen** [comment]
Oops, you're right.

**Comment by cwmeijer** [comment]
It works now! Created a nice pointcloud too! I'll show you on monday. Thanks!
